name: new-linux3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
      - name: Downloading & Setting Up
        run: |
         sudo apt-get update
         sudo apt-get install tmate neofetch -y
         tmate -F -n web new-session sudo su
